name: Minutes Forecast Run

on: push
  #schedule:
  #  - cron: '0 14 * 4,5,6,7,8,9 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - run: pip install -r requirements.txt
    - run: python3 src/ros_minutes_projections.py -c ${{ secrets.SERVICE_BLOB }}
